CREATE TABLE mock_provider (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    provider_code VARCHAR(64) NOT NULL,
    provider_name VARCHAR(128) NOT NULL,
    owner VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_by VARCHAR(128) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_provider_code (provider_code),
    INDEX idx_provider_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mock_api (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    provider_id BIGINT NOT NULL,
    api_code VARCHAR(64) NOT NULL,
    api_name VARCHAR(128) NOT NULL,
    http_method VARCHAR(16) NOT NULL,
    path VARCHAR(512) NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    owner VARCHAR(128) NOT NULL,
    status VARCHAR(32) NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_by VARCHAR(128) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    UNIQUE KEY uk_api_provider_code (provider_id, api_code),
    INDEX idx_api_provider_status (provider_id, status),
    CONSTRAINT fk_api_provider FOREIGN KEY (provider_id) REFERENCES mock_provider (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mock_contract_version (
    id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    api_id BIGINT NOT NULL,
    version_no INT NOT NULL,
    status VARCHAR(32) NOT NULL,
    request_schema_json JSON NOT NULL,
    response_schema_json JSON NOT NULL,
    examples_json JSON NULL,
    error_codes_json JSON NULL,
    business_key_extractor_json JSON NULL,
    signature_metadata_json JSON NULL,
    source_type VARCHAR(32) NOT NULL,
    source_file_hash CHAR(64) NULL,
    checksum CHAR(64) NOT NULL,
    created_by VARCHAR(128) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    published_by VARCHAR(128) NULL,
    published_at TIMESTAMP(6) NULL,
    UNIQUE KEY uk_contract_api_version (api_id, version_no),
    UNIQUE KEY uk_contract_api_checksum (api_id, checksum),
    INDEX idx_contract_api_status (api_id, status),
    CONSTRAINT fk_contract_api FOREIGN KEY (api_id) REFERENCES mock_api (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE mock_request_log (
    id VARCHAR(64) NOT NULL,
    mock_request_id VARCHAR(64) NOT NULL,
    trace_id VARCHAR(64) NULL,
    environment VARCHAR(32) NOT NULL,
    app_code VARCHAR(128) NOT NULL,
    tenant_code VARCHAR(128) NULL,
    test_account_masked VARCHAR(256) NULL,
    provider_code VARCHAR(64) NOT NULL,
    api_code VARCHAR(64) NOT NULL,
    scenario_id VARCHAR(64) NULL,
    scenario_version_id VARCHAR(64) NULL,
    release_id VARCHAR(64) NULL,
    flow_key VARCHAR(128) NULL,
    business_no_hmac CHAR(64) NULL,
    hmac_key_version VARCHAR(32) NULL,
    http_method VARCHAR(16) NOT NULL,
    path VARCHAR(1024) NOT NULL,
    request_summary VARCHAR(4096) NULL,
    response_summary VARCHAR(4096) NULL,
    http_status SMALLINT UNSIGNED NULL,
    match_result VARCHAR(64) NOT NULL,
    duration_ms BIGINT UNSIGNED NOT NULL,
    error_code VARCHAR(64) NULL,
    expire_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (created_at, id),
    INDEX idx_request_log_id (id),
    INDEX idx_request_log_app_request (app_code, mock_request_id, created_at),
    INDEX idx_request_log_trace (trace_id),
    INDEX idx_request_log_business (hmac_key_version, business_no_hmac),
    INDEX idx_request_log_provider_api (provider_code, api_code, created_at),
    INDEX idx_request_log_scenario (scenario_id, created_at),
    INDEX idx_request_log_expire (expire_at),
    INDEX idx_request_log_created (created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

ALTER TABLE mock_audit_log
    CHANGE COLUMN operator_id `operator` VARCHAR(128) NOT NULL,
    CHANGE COLUMN action_code `action` VARCHAR(64) NOT NULL,
    CHANGE COLUMN target_type object_type VARCHAR(64) NOT NULL,
    CHANGE COLUMN target_id object_id VARCHAR(128) NULL,
    CHANGE COLUMN details_masked after_json_masked JSON NULL,
    ADD COLUMN object_checksum CHAR(64) NULL AFTER object_id,
    ADD COLUMN before_json_masked JSON NULL AFTER object_checksum,
    ADD COLUMN result VARCHAR(32) NOT NULL DEFAULT 'SUCCESS' AFTER after_json_masked,
    ADD COLUMN reason VARCHAR(512) NULL AFTER result,
    ADD INDEX idx_audit_operator_created (`operator`, created_at),
    ADD INDEX idx_audit_object_created (object_type, object_id, created_at),
    ADD UNIQUE KEY uk_audit_request_action_object (request_id, `action`, object_id);
